### ISSUE TITLE
Patch nvram iGPU

### ISSUE THREAD

**Issue by truongvantuan** [ChefKissInc/NootedRed#112]
Can i patch nvram for get 1GB nvram?

**Screenshots**
![image](https://github.com/NootInc/NootedRed/assets/22904956/d0e838e8-baa1-4380-ab11-83f5f59140d0)

**System Information:**
 - macOS Version: Ventura 13.4.1
 - CPU: AMD Ryzen 7 4700GE
 - iGPU: Radeon Vega 8 Graphics

**Comment by ChefKissInc** [comment]
“Bug”
`Smokeless-UMAF`
