### ISSUE TITLE
System stalls at installation phase right before Setup Assistant

### ISSUE THREAD

**Issue by jalavoui** [ChefKissInc/NootedRed#125]

**Comment by ChefKissInc** [comment]
It is a Lilu issue. It does not detect the last installation phase (before setup assistant). I have filed this bug like several months ago.

**Comment by ChefKissInc** [comment]
@jalavoui Haha

**Comment by ChefKissInc** [comment]
External: acidanthera/bugtracker#2286

**Comment by ChefKissInc** [comment]
By proposed fix I meant yours. It causes a kernel panic

**Comment by GoldPotato7** [comment]
I know it is late... I am facing the exact same issue in bigsur, I know this is the wrong thread, but what was the solution 🤦

**Comment by VisualEhrmanntraut** [comment]
Disabling NRed and reenabling it or waiting 10 minutes. Complain to Acidanthera.

**Comment by GoldPotato7** [comment]
I just read your old threads finally booted into setup after 3 day THANK YOU SO MUCH ☺️☺️☺️

**Comment by GoldPotato7** [comment]
nd is it normal for it to be a Lil laggy at first?

**Comment by VisualEhrmanntraut** [comment]
The issues aren't for asking for help. But this signals a TSC sync issue, try adding https://github.com/Seey6/CpuTscSync

**Comment by GoldPotato7** [comment]
With nooted red enabled?

**Comment by VisualEhrmanntraut** [comment]
I assumed that the lagginess was with NRed enabled.

**Comment by GoldPotato7** [comment]
No, it is disabled rn, I am in setup and it is almost unusable, but I'm patiently getting through it...

**Comment by GoldPotato7** [comment]
I reached the home window, it was black, but all is functioning... Still laggy... Should I use both nred and tscsync?

**Comment by VisualEhrmanntraut** [comment]
As I said, the issues are not for support. Join the Telegram linked in our site for support.

**Comment by VisualEhrmanntraut** [comment]
Fixed in latest commit.

**Comment by AlfCraft07** [comment]
No this issue is not what you described. It is the fact that, during the last Apple logo phase (before X minutes left) it just stops at an "IOKit daemon stall iGPU" error, visible with verbose. It's fixed now.

**Comment by nononymousse** [comment]
oh oki, thanks for the explanation ^^

that mean no more disabling NootedRed when doing a update too ?

**Comment by AlfCraft07** [comment]
> oh oki, thanks for the explanation ^^
> 
> that mean no more disabling NootedRed when doing a update too ?

Exactly that

**Comment by VisualEhrmanntraut** [comment]
> if i understood correctly, the issue is that when booting on the out of box experience (enter user info, migration from another mac, etc) it crashes. i had that issue before on Sonoma at that stage where i get the grey background, cursor, then color wheel and crashes. i booted on a second partition that is at that stage to see if it has evolved and i just tried it with the commit from 10 hours ago and still the same thing.
> 
> if that’s the issue was for and if you want i can send you the logs for it (dunno where they are tho)
> 
> thanks again for your work ^^

This issue you're referring to is #235.
