### ISSUE TITLE
How do I increase VRAM size?

### ISSUE THREAD

**Issue by Trijal08** [ChefKissInc/NootedRed#156]
I see in the NootedRed website from Wayback Machine that I should increase my VRAM size, HOW DO I DO IT!?

Please and Thank You!

**Comment by VisualEhrmanntraut** [comment]
@Trijal08 Bro, our site is still up; it just got moved to “chefkissinc” instead of “nootinc”. Also, Smokeless-UMAF. This isn’t an “issue”.

**Comment by Trijal08** [comment]
> @Trijal08 Bro, our site is still up; it just got moved to “chefkissinc” instead of “nootinc”. Also, Smokeless-UMAF. This isn’t an “issue”.

What the heo is a Smokeless-UMAF?

**Comment by cornshiba** [comment]
A tool to change hidden bios settings for AMD Laptops.

**Comment by Trijal08** [comment]
> A tool to change hidden bios settings for AMD Laptops.

What is the default VRAM set in BIOS? Is it max?

**Comment by cornshiba** [comment]
What? For me its Auto. Smokeless-UMAF Isn't modding the bios. It is just a bootable tool to change hidden bios settings.

**Comment by Trijal08** [comment]
> What? For me its Auto. Smokeless-UMAF Isn't modding the bios. It is just a bootable tool to change hidden bios settings.

OK case closed!
