### ISSUE TITLE
Raven1/Picasso gets an immediate compute crash then reboot since latest firmware logic

### ISSUE THREAD

**Issue by AbhishekOjha08** [ChefKissInc/NootedRed#159]
**Describe the bug**
I copied the NootedRed kext and removed whatevergreen. Also cleared nvrm 3 times but i cannot get into the desktop. As soon as I enter my password, it keeps on loading and then crashes and reprompts for login password.

**To Reproduce**
1. copy NootedRed kext to the efi and change smbios to iMac20,1  and then tried IMac7,1 

**Expected behavior**
I believe the kext is working because the general mouse movement fluency and transparency is visible. I was able to get into desktop once and it was still loading and then it crashed after a while. And let me make this clear, the system was unusable, dock didn't show up. I changed nothing 

**Screenshots**

![Screenshot_20230906-174417_Gallery](https://github.com/ChefKissInc/NootedRed/assets/82158818/107818ac-f39b-4ade-a6e6-036c4ced9a15)

![Screenshot_20230906-174417_Gallery](https://github.com/ChefKissInc/NootedRed/assets/82158818/8f0a4546-bb2e-405f-834f-bbc606eb514b)

**System Information:**
 - macOS Version: [macOS 11.7.9]
 - CPU: [AMD Ryzen 3 3200G]

 - Motherboard : MSI b450 Tomahawk Max
 - RAM : 2x8GB

**Additional context**
I have used Olarila's Vanilla iso.

**Comment by VisualEhrmanntraut** [comment]
We don't support Olarila. Don't use anything from them for your own good.

However, there is indeed a compute hang issue on Raven.

**Comment by MixedVictor** [comment]
Same here after downloading the latest version, I had to disable autologin to see what was happening. After trying to log in, it would just freeze and crash the system, I got a [kernel panic log](https://textbin.xyz/?6ba048a08db34415#zD4DQwGN6qkQabPaKf85KcH8k55wD6SgtR5VgMGe8q3) if that will help anyone. Also, I'm using a Ryzen 7 3700U.

**Comment by VisualEhrmanntraut** [comment]
Commenting out the MEC firmware injection works around the issue. But that's not a solution.

**Comment by VisualEhrmanntraut** [comment]
I look forward to it. ~~Provided it's not just disabling MEC or something~~

**Comment by VisualEhrmanntraut** [comment]
@jalavoui All the new firmware is taken straight from Windows.

**Comment by VisualEhrmanntraut** [comment]
@jalavoui Eh, don’t worry about it.
