### ISSUE TITLE
Can't fetch right hwlibs

### ISSUE THREAD

**Issue by hi-august** [ChefKissInc/NootedRed#160]
**To Reproduce**
1. I used CI #1023 kext crashed

**Screenshots**

![CI #1023](https://github.com/ChefKissInc/NootedRed/assets/7383501/e45355ab-75d1-4fa0-8eb4-c7e6a459d565)
![CI #1019](https://github.com/ChefKissInc/NootedRed/assets/7383501/79e4024d-1d31-4724-b607-345e539288cf)

**System Information:**
 - macOS Version: macOS10.15
 - CPU: AMD Ryzen 7 4800U

**Comment by VisualEhrmanntraut** [comment]
Outdated kext

**Comment by VisualEhrmanntraut** [comment]
@hi-august That was just a README change

**Comment by VisualEhrmanntraut** [comment]
I am talking about your screenshots. That's from before CI#1023. CI#1023 crashing is #159

**Comment by hi-august** [comment]
<img width="419" alt="截屏2023-09-06 下午8 49 48" src="https://github.com/ChefKissInc/NootedRed/assets/7383501/83eda0f4-18fd-4169-b24d-9541e6b88f49">
it(CI #1019) boots sucess,crashed CI#1024

**Comment by VisualEhrmanntraut** [comment]
Failure screenshot is cut in half; useless.
