### ISSUE TITLE
Electron apps freeze system, turn red, crash/start

### ISSUE THREAD

**Issue by Otus9051** [ChefKissInc/NootedRed#174]
**Describe the bug**

**To Reproduce**
1. Open any Electron App (consider VSCode)
2. Observe
3. See error

**Expected behavior**
It works without freezing the system.

**Screenshots**
![](https://media.discordapp.net/attachments/918054095640743937/1151831146485780480/IMG_20230914_161535.jpg)
![](https://media.discordapp.net/attachments/918054095640743937/1151535319540318218/IMG_20230913_161957.jpg)

**System Information:**
 - macOS 13.5.2
 - CPU: AMD Ryzen 3 5300U
 - VRAM: 512MB (cannot extend because HP Laptop)

**Additional context**
Here's some l logs I managed to capture
[message.txt](https://github.com/ChefKissInc/NootedRed/files/12611726/message.txt)

**Comment by ExtremeXT** [comment]
@Otus9051 Increase VRAM with Smokeless-UMAF. Also, what's your laptop model? I also have an HP with a 5300U, just interested.

**Comment by Otus9051** [comment]
HP-15s EQ2144AU.
Thanks for the suggestion, will try tomorrow.

**Comment by Otus9051** [comment]
After trying the suggestion and setting VRAM to 2GB, everything seems fine. Closing issue as solved.
