### ISSUE TITLE
AmdDalHelper::powerUp NMIPI on boot

### ISSUE THREAD

**Issue by xandeale** [ChefKissInc/NootedRed#175]
Hello, I can't reach any GUI, computer crashes and/or reboots during verbose after opencore selection, resulting in a black screen (monitor loses connection). Disabling Nootedred fixes the problem but pc boots without graphics acceleration. Apps like VLC and Safari browser are bugged and unusable without acceleration.

It shows some errors during boot verbose like "couldn't alloc applekeystoretest" , "can't build index" , "not eligible for acceleration" and a lot of others, but it can boot normally if nootedred enabled is set as "false".

**Expected behavior**
I expected to reach any graphical interface, even with some minor glitches, but nothing shows on screen, only the verbose if you enable -v boot-args.

**System Information:**

 - Mac OS Sonoma
 - CPU: AMD Ryzen 5 5600G
 - Motherboard: Gigabyte A520M-DS3H - Bios version: F10
 - RAM: 2x Kingston 8GB 2666Mhz

**Comment by ExtremeXT** [comment]
@xandeale What SMBIOS are you on? The keystore "errors" are harmless and can be ignored. the SSDT is also unrelated, but you should not use the prebuilt SSDT-CPUR from Dortania. I suggest you join our Telegram group for receiving better help, the link is on our webpage alongside our AMD Hackintosh guide, which explains how to properly gather the SSDTs.

**Comment by xandeale** [comment]
imacpro1,1 , i tried others and it doesn't change anything

**Comment by ExtremeXT** [comment]
@xandeale iMacPro1,1 and MacPro6,1 (and perhaps MacPro6,1?) are NOT recommended because those Macs do not have iGPUs. Desktops should use iMac20,1. The Telegram group way of communicating still stands.

**Comment by xandeale** [comment]
it crashed and rebooted with iMac20,1 too, i think it is another problem that needs to be fixed

**Comment by VisualEhrmanntraut** [comment]
Are you using AmdTscSync?

**Comment by xandeale** [comment]
yes, i enabled it with 11 on IOCPUNumber is it right?? but nothing changes

**Comment by VisualEhrmanntraut** [comment]
No, that's incorrect for Monterey in newer; it needs to be 0. However, AmdTscSync will cause problems if you don't need it.

**Comment by dajiba36cm** [comment]
> 不，这对蒙特雷和更新者来说是不正确的;它需要为 0。但是，如果您不需要AmdTscSync，则会导致问题。

Which should be used for 0 and -1？

**Comment by VisualEhrmanntraut** [comment]
@dajiba36cm -1? Who said that? Do you have 255 threads? 🤣

**Comment by dajiba36cm** [comment]
> -1？谁说的？你有 255 个线程吗？🤣

The author wrote -1 in the Github introduction

**Comment by VisualEhrmanntraut** [comment]
@dajiba36cm Number of threads minus one

**Comment by xandeale** [comment]
i wonder if anyone succeeded activating it with this motherboard or chipset lol

**Comment by dajiba36cm** [comment]
> 线程数减去 1

Taking 5800H as an example, I have never understood whether to fill in 0 or -1 or 15

**Comment by xandeale** [comment]
better to disable amdtscsync then

**Comment by VisualEhrmanntraut** [comment]
> computer crashes and/or reboots during verbose after opencore selection
Can you be more precise? How early is it rebooting?

**Comment by xandeale** [comment]
boot verbose messages appear the same way as without nootedred , but after a few minutes of messages showing up on screen, right at the moment the apple logo should appear, monitor loses signal and keyboard lights go off and computer reboots

**Comment by xandeale** [comment]
so... any news about my bug? i see that title has changed. I tried the new version of nred but didn't work :(
There is a guy i'm talking with doing a hackintosh on Gigabyte B550M aorus elite and R5 5600G and he was able to use hardware acceleration without issues. I tried his EFI and i have the same error...

**Comment by xandeale** [comment]
[nred_error_log_sonoma.txt](https://github.com/ChefKissInc/NootedRed/files/12732110/nred_error_log_sonoma.txt)

**Comment by xandeale** [comment]
It didn't work @jalavoui , it crashed again and rebooted.

**Comment by VisualEhrmanntraut** [comment]
Was it ever working?

**Comment by xandeale** [comment]
it never worked for me

**Comment by VisualEhrmanntraut** [comment]
Issue mislabeled

**Comment by xandeale** [comment]
hi, i took the risk and updated successfully my bios to F17 , now it boots :)

**Comment by ExtremeXT** [comment]
Resolved by updating the BIOS.
