### ISSUE TITLE
When I enable nootedred, I get stuck

### ISSUE THREAD

**Issue by TwilightNougat** [ChefKissInc/NootedRed#180]
**Describe the bug**

If I don't enable nootedred, I can boot the system normally, but when I enable nootedred, it will get stuck on the last line in -v mode.I tried big sur and Monterey with the same result. I don't know how to debug or get the output log

**To Reproduce**
1. Install the system **without** enabling nootedred
2. After booting to the desktop for the first time, **enable** nootedred
3. Then reboot
4. Seeing the error, stuck at the end of the -v output

**Expected behavior**
In the Windows, i can see that the default graphics output is rx 6400. At first, I thought it was a problem with the discrete graphics card's default output, so I used the SSDT-NoHybGfx patch to disable rx6400, but to no avail. I found that the BIOS name of my IGPU  is different from other people's. I don't know if this has any impact. I plan to try the rename patch next.

**Screenshots**
[XHCI and usb port](https://github.com/TwilightNougat/tianbaoEFI/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-10-01%20124752.png)
[computer hardware](https://github.com/TwilightNougat/tianbaoEFI/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-10-01%20124808.png)
[graphics device](https://github.com/TwilightNougat/tianbaoEFI/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-10-01%20124858.png)

**System Information:**
 - macOS Version: macOS Big Sur 11.7.9 (20G1426) and macOS Monterey 12.6.8(21G725) 
 - CPU: AMD Ryzen 7 5800h
 - IGPU: AMD Radeon(TM) Graphics (BIOS Name: \_SB.PCI0.GP17.VGA)
 - dGPU: AMD Radeon RX 6400 (BIOS Name: \_SB.PCI0.GPP0.SWUS.SWDS.VGA) Close with SSDT-NoHybGfx

**Additional context**
I blocked an XCHI and used the Rename PEGP to GFX0 and Rename GFX0 to IGPU patches (of course I tried not doing this and couldn't enable nootedred). My boot-args only have -v
my config: [config.plist](https://github.com/TwilightNougat/tianbaoEFI/blob/main/config.plist)
here is [SSDT-NoHybGfx.dsl](https://github.com/TwilightNougat/tianbaoEFI/blob/main/SSDT-NoHybGfx.dsl)

**Comment by SalmonPete** [comment]
Might be a silly question, when do you disable NootedRed and reboot, have you then enabled WhateverGreen for your GPU?. Second silly question, do you have any device properties in your EFI for the GPU?, if so you'd have to remove them for NootedRed to boot.

**Comment by TwilightNougat** [comment]
> Remove the Device Properties from Your Plist.

Thank you very much for your reply. But I did not enable any graphics driver except nootedred.kext, nor whatevergreen. I also tried without adding any DP before, but it still didn't work. I followed the tutorials on the website exactly [https://chefkissinc.github.io/nred](https://chefkissinc.github.io/nred) 
By the way, I am using HDMI port and I don’t have a DP video cable, I guess it might have something to do with the video output port? Although it is unlikely, I have tried everything I can now

**Comment by TwilightNougat** [comment]
> Remove the Device Properties from Your Plist. I see 'RestrictEvents' in your EFI, add **revblock=media** to your boot args.

Thank you, I will try it now

**Comment by SalmonPete** [comment]
Have you asked over at AMD OS X?.

**Comment by VisualEhrmanntraut** [comment]
Maybe it would work if you were not using a prebuilt EFI + configurator.
