### ISSUE TITLE
Ryzen 7 5700G bugs with DP and acceleration

### ISSUE THREAD

**Issue by sasdallas** [ChefKissInc/NootedRed#185]
**Describe the bug**
On the Ryzen 7 5700G, I experience very strange behavior:

**DP Issues**
When I boot up macOS, I cannot have both of my monitors (1 DP and 1 HDMI) plugged into the iGPU, as after gIOLockScreen I just get a black screen with no output (just "No Signal"). If I have my HDMI monitor plugged into the iGPU and my DP monitor plugged into dGPU (unsupported GPU, NVIDIA RTX 3070), the iGPU monitor boots to lock screen, and I can unplug the DP monitor and plug it into iGPU and use macOS.

TL;DR: macOS only shows up if the DP monitor is not plugged in on boot, and DP monitor works only after plugging it after first lock screen.

**Acceleration issues**
VDADecoderChecker shows error -12473, but some graphics acceleration is present (taskbar is slightly transparent and windows move okay).

**To Reproduce**
1. Have two monitors, one using HDMI and one using DP.
2. Plug both monitors into iGPU.
3. Profit (or in this case, don't)

**Expected behavior**
I don't have to play stupid games with my GPUs and VDADecoderChecker outputs success.

**Screenshots**
insert black screen

**System Information:**
 - macOS Version: macOS 11.7.10
 - CPU: AMD Ryzen 7 5700G
 - (Unsupported) dGPU: NVIDIA RTX 3070
- SMBIOS: iMac20,1

**Additional context**
- I removed WhateverGreen
- Display freezes up when too much is happening.

**Comment by VisualEhrmanntraut** [comment]
The VDA stuff is just #28. The DP stuff seems to also be #52. Unfortunately, these issues are very complicated, reiterating over already known issues won't help us fix them
