### ISSUE TITLE
Enabling nootedred prevents me from entering the system

### ISSUE THREAD

**Issue by ShevonKuan** [ChefKissInc/NootedRed#189]
**Describe the bug**

I did not enable nootedred when installing the system. After the installation was completed, I could successfully enter the system.  But when I enabled nootedred I got stuck on the following screen.  The content of this screen keeps looping and cannot be entered into the system. Maybe this is my problem instead of a bug.

**To Reproduce**

After enabling, the problem occurs. After disabling, the problem is solved and you can enter the system.

**Expected behavior**

**Screenshots**

![IMG_20231025_100839.jpg](https://github.com/ChefKissInc/NootedRed/assets/49824574/e4733862-0889-4066-ad25-dd8652e653fe)

**System Information:**
 - macOS Version: 13.5.1
 - CPU:  AMD Ryzen 7 4800u
 - wifi: Intel ax210
 - SSD: wd sn750

**Comment by VisualEhrmanntraut** [comment]
@ShevonKuan https://chefkissinc.github.io/nred#prerequisites

**Comment by ShevonKuan** [comment]
Thank you.  I followed this tutorial and I'm pretty sure I met all the prerequisites.  For example, my computer does not have a discrete graphics card and I have allocated 2g of video memory for the vega8 core display.

**Comment by VisualEhrmanntraut** [comment]
Closing as this issue seems to be user error.

**Comment by ryanloee** [comment]
According to this document, the problem still occurs ：(
