### ISSUE TITLE
A minority of apps have an SDMA crash on macOS 11 and newer

### ISSUE THREAD

**Issue by nanohelperDev** [ChefKissInc/NootedRed#192]
Hello dear,
i face it problem when trying apps like Fl studio and zbrush , its not opening
when i use it fl studio 20 he worked fine but the screen its flickering  but when i upgrade it to version fl studio 21 when i click to open them , he start loading but he make the system crash stuck in loading icon on mouse,

for zbrush he wont open at all , but for me blender and unity 3d working fine also google chrome i disable hardware acceleration on it to make it run without stuck at first, 

Also virtual box and vmweare fusion , not start machine , when i create new machine he exit the app

my spec its :

Amd rayzen 5625u, Vram 2GB
16Gb ram
HP laptop 15s-eq3XXX

Thanks in advance

**Comment by VisualEhrmanntraut** [comment]
Can you retry those apps with the latest commit?

**Comment by nanohelperDev** [comment]
Hello My friend , i can confirme its still the same problem , but when i disable nootedred and run with whatevergreen , he work normally but laggy you know.

**Comment by VisualEhrmanntraut** [comment]
Using WhateverGreen on an AMD iGPU is the same as not having it, because it does nothing :-)

**Comment by nanohelperDev** [comment]
yees sure ;) , also all adobe apps working correcly without any problem exporting and importing everything fine without any third party tool , and the softwares rendering like blender and unity.........etc , works perfectly

**Comment by nanohelperDev** [comment]
the new version of Zbrush its working right now , on the last update :)

**Comment by nanohelperDev** [comment]
Also for crossover i try it a game on windows , solitair3 and its working fine , and softwares working fine , but games not as you mention before , Thanks

**Comment by nanohelperDev** [comment]
Hello new news, i can confirme thats unreal engine 4 / 5 doesn't use graphics acceleration , its laggy sometimes red screen , sometimes get out automatically

**Comment by VisualEhrmanntraut** [comment]
Please retry with the latest commit.

**Comment by szmarczak** [comment]
I volunteered and:
- FL Studio works like a charm
- Google Chrome launches but is unusuable, if you try to type anything in the address bar the entire screen freezes for like 30 seconds and can't do anything (except the mouse)
- haven't tested other apps yet

**Comment by VisualEhrmanntraut** [comment]
Chrome and etc is just #158

**Comment by VisualEhrmanntraut** [comment]
Reports seem to suggest this is fixed now, so closing this. Comment if you are still experiencing the issue with latest commit :)
