### ISSUE TITLE
Catalina result in black screen

### ISSUE THREAD

**Issue by Tang061022Tang** [ChefKissInc/NootedRed#196]
As the title said, I tried to boot Catalina recoveryOS but it resulted in black screen and no responded. Does the project has this bug?
R5-3550H, Radeon Vega 8 2GB

**Comment by ExtremeXT** [comment]
@Tang061022Tang Try this build.
https://github.com/ChefKissInc/NootedRed/actions/runs/6580078043

**Comment by Tang061022Tang** [comment]
It works but when I tried to adjust the brightness, my screen will be black
That means it only works in the highest brightness

**Comment by VisualEhrmanntraut** [comment]
@Tang061022Tang Catalina does not support brightness control for AMD GPUs. Use an app like Lunar

**Comment by Tang061022Tang** [comment]
Thx, I succeed
