### ISSUE TITLE
Problem on CrossOver and PlayOnmac , crash when starting games, but generaly in programs doesnt use render 3d work

### ISSUE THREAD

**Issue by nanohelperDev** [ChefKissInc/NootedRed#198]
Hello dear, Thanks for thats work you are doing its great work. 
i face it recently a problem when i want start a game or steam program on crossover or playonmac , the system freeze at all and cant do anything than i need it to force restart them , i dont know if thats problem only i facing them or everyone.

Myspece rayzen 5 5625i, RAM 16GB

**Comment by VisualEhrmanntraut** [comment]
Duuuuuuuuplicate of #158

**Comment by nanohelperDev** [comment]
Okay sure , thanks
