### ISSUE TITLE
All application windows cannot be rendered properly after increased iGPU vRAM to 1g/2g

### ISSUE THREAD

**Issue by itzdrli** [ChefKissInc/NootedRed#203]
### macOS Version

Sonoma

### What is your CPU's model?

AMD R7 5800H

### Please describe the behaviour in detail.

after using the nootedred with only igpu, i was facing performance issue: screen freeze for seconds or minutes, laggy actions etc. Someone told me try to increase vRAM via Somkeless-UMAF, this is what I did: 
![image](https://github.com/ChefKissInc/NootedRed/assets/52338732/06a811e6-aa1c-4f69-a27d-acf93985379d)
and this is what happend after I logged in and opened some window, my screen truned to be like this:
![IMG_20231126_124935266](https://github.com/ChefKissInc/NootedRed/assets/52338732/fdc195f9-2563-4c19-98fa-64d981932a62)

### What should've happened instead?

All application windows should be rendered properly

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
***Which app?***

**Comment by itzdrli** [comment]
> _**Which app?**_

all apps, including the top bar of the system

**Comment by VisualEhrmanntraut** [comment]
Which app did you launch before that happened

**Comment by itzdrli** [comment]
> Which app did you launch before that happened

google chrome, 1password, about this mac, settings

**Comment by VisualEhrmanntraut** [comment]
Google Chrome and 1Password are both OpenGL apps.

**Comment by itzdrli** [comment]
> Google Chrome and 1Password are both OpenGL apps.

but other apps are acting same, even I closed chrome and 1pass

**Comment by VisualEhrmanntraut** [comment]
Because the VRAM got corrupted after you launched them

**Comment by itzdrli** [comment]
> Because the VRAM got corrupted after you launched them

so is there any fix for this situation?

**Comment by VisualEhrmanntraut** [comment]
Just restart your machine and delete the apps for now
