### ISSUE TITLE
picasso reset hang

### ISSUE THREAD

**Issue by jalavoui** [ChefKissInc/NootedRed#208]
### macOS Version

Ventura

### What is your CPU's model?

ryzen 3

### Please describe the behaviour in detail.

try in console (with sublime gpu aceleration enabled) + bfixup.kext

 /Applications/Utilities/Sublime\ Text.app/Contents/MacOS/sublime_text

### What should've happened instead?

the driver try reset and panic

possible fix:
this shouldnt work for picasso but actually stops the panic

          //  if (NRed::callback->chipType >= ChipType::Renoir) {
                RouteRequestPlus request {"_psp_reset_3_1", psp12Reset, kPspReset31Pattern};
                PANIC_COND(!request.route(patcher, id, slide, size), "HWLibs", "Failed to route psp_reset_3_1");
          //  } else {
           //     RouteRequestPlus request {"_psp_reset_3_1", hwLibsUnsupported, kPspReset31Pattern};
          //      PANIC_COND(!request.route(patcher, id, slide, size), "HWLibs", "Failed to route psp_reset_3_1");
          //  }

the metal api hangs a bit as this is a extreme bug but
the system recovers

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

[Kernel-2023-12-07-140131.panic.zip](https://github.com/ChefKissInc/NootedRed/files/13601701/Kernel-2023-12-07-140131.panic.zip)

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
This condition is impossible to be met on Picasso
