### ISSUE TITLE
boot loop when nootedred.text enabled

### ISSUE THREAD

**Issue by CrotchBurnt** [ChefKissInc/NootedRed#217]
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 7 5825U

### Please describe the behaviour in detail.

It works well while installing but it turns into forever boot loop even if only Lilu、VirtualSMC、Nootedred enabled. When I disable NRed only, I could enter the system. 
![IMG_6732](https://github.com/ChefKissInc/NootedRed/assets/6418433/23f1d894-0ec3-44c5-ae20-7b190c5655a8)

### What should've happened instead?

Booting into the system

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

`{"bug_type":"210","timestamp":"2024-01-10 21:26:13.00 +0800","os_version":"macOS 14.2.1 (23C71)","roots_installed":0,"incident_id":"3B5AC2BD-D27A-46C4-9861-1B1AA2A34C61"}`
`{"macOSProcessedStackshotData":"bm8gb24gZGlzayBwYW5pYyBzdGFja3Nob3QgZm91bmQgaW4gY29yZWZpbGU=","macOSPanicString":"panic(cpu 10 caller 0xffffff8016f84f03): Kernel trap at 0xffffff7fa3584bfe, type 14=page fault, registers:\nCR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x00000001e8743000, CR4: 0x00000000003406e0\nRAX: 0x0000000000000000, RBX: 0xffffffd0540f76f0, RCX: 0xd3b092fee04f008f, RDX: 0xfffffffffffffffe\nRSP: 0xffffffd0540f76c0, RBP: 0xffffffd0540f76e0, RSI: 0x00000000001fa180, RDI: 0x0000000000000000\nR8:  0x0000000000000000, R9:  0xffffff7fa3747c8b, R10: 0x0000000000000001, R11: 0x0000000000000000\nR12: 0x0000000074677374, R13: 0x000000000000000e, R14: 0xffffffffff23e000, R15: 0x0000000000000000\nRFL: 0x0000000000010246, RIP: 0xffffff7fa3584bfe, CS:  0x0000000000000008, SS:  0x0000000000000010\nFault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0xa, PL: 0, VF: 0\n\nPanicked task 0xffffff8b76a63be8: 7 threads: pid 144: WindowServer\nBacktrace (CPU 10), panicked thread: 0xffffff904245e0c8, Frame : Return Address\n0xffffffd0540f7040 : 0xffffff8016e36c41 mach_kernel : _handle_debugger_trap + 0x4b1\n0xffffffd0540f7090 : 0xffffff8016f95310 mach_kernel : _kdp_i386_trap + 0x110\n0xffffffd0540f70d0 : 0xffffff8016f84a5c mach_kernel : _kernel_trap + 0x55c\n0xffffffd0540f7150 : 0xffffff8016dd3971 mach_kernel : _return_from_trap + 0xc1\n0xffffffd0540f7170 : 0xffffff8016e36f2d mach_kernel : _DebuggerTrapWithState + 0x5d\n0xffffffd0540f7260 : 0xffffff8016e365d3 mach_kernel : _panic_trap_to_debugger + 0x1e3\n0xffffffd0540f72c0 : 0xffffff80175d8bcb mach_kernel : _panic + 0x84\n0xffffffd0540f73b0 : 0xffffff8016f84f03 mach_kernel : _sync_iss_to_iks + 0x2c3\n0xffffffd0540f7530 : 0xffffff8016f84be7 mach_kernel : _kernel_trap + 0x6e7\n0xffffffd0540f75b0 : 0xffffff8016dd3971 mach_kernel : _return_from_trap + 0xc1\n0xffffffd0540f75d0 : 0xffffff7fa3584bfe com.apple.kext.AMDRadeonX6000Framebuffer : __ZN35AMDRadeonX6000_AmdRadeonFramebuffer12getAttributeEjPm + 0x296\n0xffffffd0540f76e0 : 0xffffff7f9ba2b51a com.apple.kext.AMDRadeonX5000 : __ZN34AMDRadeonX5000_AMDAccelDisplayPipe28writeFbTriageDiagnosisReportERPcRj + 0x9a\n0xffffffd0540f7720 : 0xffffff7f9ba21dba com.apple.kext.AMDRadeonX5000 : __ZN37AMDRadeonX5000_AMDGraphicsAccelerator20writeDiagnosisReportERPcRj + 0x42e\n0xffffffd0540f7770 : 0xffffff7f9ba261d2 com.apple.kext.AMDRadeonX5000 : __ZN30AMDRadeonX5000_AMDAccelChannel26getHardwareDiagnosisReportEPj + 0x1e2\n0xffffffd0540f77c0 : 0xffffff7fabc1b8b6 com.apple.iokit.IOAcceleratorFamily2 : __ZN19IOAccelFIFOChannel27restartEv + 0x10a\n0xffffffd0540f7810 : 0xffffff7fabc29ea6 com.apple.iokit.IOAcceleratorFamily2 : __ZN20IOAccelEventMachine215restart_channelEv + 0xf6\n0xffffffd0540f7850 : 0xffffff7fabc29d9b com.apple.iokit.IOAcceleratorFamily2 : __ZN20IOAccelEventMachine226handleFinishChannelRestartEiij + 0x109\n0xffffffd0540f7880 : 0xffffff7fabc479d9 com.apple.iokit.IOAcceleratorFamily2 : __ZN24IOAccelEventMachineFast211finishStampEi + 0xd1\n0xffffffd0540f78d0 : 0xffffff7fabc47a95 com.apple.iokit.IOAcceleratorFamily2 : __ZN24IOAccelEventMachineFast215finishAllStampsEv + 0x35\n0xffffffd0540f7910 : 0xffffff7f9ba2bae1 com.apple.kext.AMDRadeonX5000 : __ZN35AMDRadeonX5000_AMDAccelEventMachine15finishAllStampsEv + 0x4d\n0xffffffd0540f7940 : 0xffffff7f9ba22324 com.apple.kext.AMDRadeonX5000 : __ZN37AMDRadeonX5000_AMDGraphicsAccelerator20callPlatformFunctionEPK8OSSymbolbPvS3_S3_S3_ + 0x3e6\n0xffffffd0540f7980 : 0xffffff7fa359bba3 com.apple.kext.AMDRadeonX6000Framebuffer : __ZNK34AMDRadeonX6000_AmdRadeonController18messageAcceleratorE25_eAMDAccelIOFBRequestTypePvS1_S1_ + 0x4f\n0xffffffd0540f79a0 : 0xffffff801a6f4f2f com.ChefKissInc.NootedRed : __ZN7X6000FB21wrapControllerPowerUpEPv + 0x9f\n0xffffffd0540f79d0 : 0xffffff7fa3561cde com.apple.kext.AMDRadeonX6000Framebuffer : __ZN35AMDRadeonX6000_AmdRadeonFramebuffer16enableControllerEv + 0x42\n0xffffffd0540f7a30 : 0xffffff7fabdc0d8e com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer4openEv + 0x634\n0xffffffd0540f7ab0 : 0xffffff7fa3561c6a com.apple.kext.AMDRadeonX6000Framebuffer : __ZN35AMDRadeonX6000_AmdRadeonFramebuffer4openEv + 0x16\n0xffffffd0540f7ad0 : 0xffffff7fabdb70c5 com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer13newUserClientEP4taskPvjPP12IOUserClient + 0x17d\n0xffffffd0540f7b60 : 0xffffff80174dab5d mach_kernel : __ZN9IOService13newUserClientEP4taskPvjP12OSDictionaryPP12IOUserClient + 0x6d\n0xffffffd0540f7bc0 : 0xffffff801754cd21 mach_kernel : _is_io_service_open_extended + 0xb1\n0xffffffd0540f7c40 : 0xffffff8016f3ffcf mach_kernel : _iokit_server_routine + 0x35ef\n0xffffffd0540f7ca0 : 0xffffff8016e0f8a0 mach_kernel : _ipc_kmsg_send + 0x570\n0xffffffd0540f7d60 : 0xffffff8016e276b8 mach_kernel : _mach_msg_overwrite_trap + 0x5d8\n0xffffffd0540f7dd0 : 0xffffff8016e27d28 mach_kernel : _mach_msg2_trap + 0x3b8\n0xffffffd0540f7ef0 : 0xffffff8016f6a052 mach_kernel : _mach_call_munger64 + 0x1f2\n0xffffffd0540f7fa0 : 0xffffff8016dd3dd6 mach_kernel : _hndl_mach_scall64 + 0x16\n      Kernel Extensions in backtrace:\n         com.ChefKissInc.NootedRed(1.0)[CAE4C0CA-DA11-3BFE-998D-F9E703407244]@0xffffff801a6ee000->0xffffff801a7fffff\n            dependency: as.vit9696.Lilu(1.6.7)[087C34D2-49F8-3FDA-8757-27E9425C9EE4]@0xffffff801a6a5000->0xffffff801a6d0fff\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[D4C79EB9-840C-3311-9033-0F582EA7E4BD]@0xffffff8019154000->0xffffff8019185fff\n         com.apple.iokit.IOGraphicsFamily(598.0)[5E698968-E66C-372A-9AE4-99934BAF7A10]@0xffffff7fabda6000->0xffffff7fabdd4fff\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[D4C79EB9-840C-3311-9033-0F582EA7E4BD]@0xffffff8019154000->0xffffff8019185fff\n         com.apple.kext.AMDRadeonX6000Framebuffer(5.0.2)[4AA0AC83-D678-35A5-992B-B84DEE857AFA]@0xffffff7fa354d000->0xffffff7fa37d5fff\n            dependency: com.apple.AppleGraphicsDeviceControl(8.1.9)[D0372C4D-E33E-3899-9EA0-67FA180354E8]@0xffffff7fab24d000->0xffffff7fab250fff\n            dependency: com.apple.iokit.IOACPIFamily(1.4)[04DDFFBA-0499-3590-B6C5-C40851E28B4F]@0xffffff8018ce6000->0xffffff8018ce7fff\n            dependency: com.apple.iokit.IOGraphicsFamily(598)[5E698968-E66C-372A-9AE4-99934BAF7A10]@0xffffff7fabda6000->0xffffff7fabdd4fff\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[D4C79EB9-840C-3311-9033-0F582EA7E4BD]@0xffffff8019154000->0xffffff8019185fff\n         com.apple.iokit.IOAcceleratorFamily2(481.0.1)[E9A83038-06B1-37D9-A1D5-079A67157081]@0xffffff7fabc16000->0xffffff7fabc80fff\n            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[ECBEE7B3-965F-310B-B11D-7969B20A5A5D]@0xffffff801849d000->0xffffff80184d3fff\n            dependency: com.apple.iokit.IOGraphicsFamily(598)[5E698968-E66C-372A-9AE4-99934BAF7A10]@0xffffff7fabda6000->0xffffff7fabdd4fff\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[D4C79EB9-840C-3311-9033-0F582EA7E4BD]@0xffffff8019154000->0xffffff8019185fff\n            dependency: com.apple.iokit.IOReportFamily(47)[7EE0B816-0F22-3141-992C-ECEA9CA4B021]@0xffffff8019196000->0xffffff8019198fff\n            dependency: com.apple.iokit.IOSurface(352.0.3)[93D55571-8050-3A8B-9159-B33939D35C99]@0xffffff80192bb000->0xffffff80192e4fff\n         com.apple.kext.AMDRadeonX5000(5.0.2)[F312B802-7044-310B-B562-BB540DC8F00B]@0xffffff7f9ba1a000->0xffffff7f9bc06fff\n            dependency: com.apple.iokit.IOAcceleratorFamily2(481.0.1)[E9A83038-06B1-37D9-A1D5-079A67157081]@0xffffff7fabc16000->0xffffff7fabc80fff\n            dependency: com.apple.iokit.IOGraphicsFamily(598)[5E698968-E66C-372A-9AE4-99934BAF7A10]@0xffffff7fabda6000->0xffffff7fabdd4fff\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[D4C79EB9-840C-3311-9033-0F582EA7E4BD]@0xffffff8019154000->0xffffff8019185fff\n            dependency: com.apple.iokit.IOSurface(352.0.3)[93D55571-8050-3A8B-9159-B33939D35C99]@0xffffff80192bb000->0xffffff80192e4fff\n\nProcess name corresponding to current thread (0xffffff904245e0c8): WindowServer\nBoot args: -v alcid=12 keepsyms=1 \n\nMac OS version:\n23C71\n\nKernel version:\nDarwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2\/RELEASE_X86_64\nKernel UUID: F73CFE5A-7EF6-3C21-AFA7-742645B733CC\nroots installed: 0\nKernelCache slide: 0x0000000016a00000\nKernelCache base:  0xffffff8016c00000\nKernel slide:      0x0000000016ae0000\nKernel text base:  0xffffff8016ce0000\n__HIB  text base: 0xffffff8016b00000\nSystem model name: MacBookPro16,3 (Mac-E7203C0F68AA0004)\nSystem shutdown begun: NO\nPanic diags file available: YES (0x0)\nHibernation exit count: 0\n\nSystem uptime in nanoseconds: 31110176814\nLast Sleep:           absolute           base_tsc          base_nano\n  Uptime  : 0x000000073e4fa313\n  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000\n  Wake    : 0x0000000000000000 0x0000000770bf9858 0x0000000000000000\nCompressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and\n\n"}`

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
https://chefkissinc.github.io/nred#prerequisites

**Comment by CrotchBurnt** [comment]
> https://chefkissinc.github.io/nred#prerequisites

Yes, I checked all that, with VRAM of 512MB. I just updated panic file

**Comment by CrotchBurnt** [comment]
probably plist has compromised by OCAT, I started from the start all over again with ProperTree, everything's fine.
