### ISSUE TITLE
macos wont boot up with nootedred.kext

### ISSUE THREAD

**Issue by Sykelo** [ChefKissInc/NootedRed#229]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 3 4300GE

### Please describe the behaviour in detail.

After successfully installing macos sonoma, I installed nootedred.kext. When I restarted it, it started to not booting, but after deleting nootedred.kext, it booted normally.

### What should've happened instead?

It should boot

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

![IMG_0925](https://github.com/ChefKissInc/NootedRed/assets/46415291/7a08d5db-7c83-426e-9438-c22c2de5a311)
![hDt7cHY](https://github.com/ChefKissInc/NootedRed/assets/46415291/798f5b8d-4019-449e-90bb-43a395daf1ae)
![IMG_0924](https://github.com/ChefKissInc/NootedRed/assets/46415291/07314009-c09c-49dd-8cfa-a9196a81a815)

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
@Sykelo Followed https://chefkissinc.github.io/nred#prerequisites?

**Comment by long-zuyang** [comment]
我在安装的时候也遇到了这个情况,你只需要使用远程桌面工具关闭高动态范围(HDR)就好

**Comment by VisualEhrmanntraut** [comment]
Timed out waiting for response.
