### ISSUE TITLE
Lenovo Yoga-14S-2020ARE, CPU4800U, mouse stuck, automatic restart, yellow screen!

### ISSUE THREAD

**Issue by yuanxun9** [ChefKissInc/NootedRed#244]
### macOS Version

Sonoma

### What is your CPU's model?

4800U

### Please describe the behaviour in detail.

Hello, my laptop is Lenovo Yoga-14S-2020ARE, with a CPU of 4800U. It uses the latest version of the graphics card driver CI # 1090: 8019036 NootedRed.kext, but the mouse is stuck and automatically restarts. Uncheck NootedRed.kext in the OC configuration file to boot up normally without a driver kernel! Could you please check the log if you have time? Thank you for your work!!

### What should've happened instead?

Mouse stuck, automatic restart, yellow screen!

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by yuanxun9** [comment]
![Screenshot_2024-04-01-18-11-18-26_99c04817c0de5652397fc8b56c3b3817](https://github.com/ChefKissInc/NootedRed/assets/49105934/cd09f136-572c-4016-9c91-db7ac23e14f3)
![Screenshot_2024-04-01-18-10-49-40_99c04817c0de5652397fc8b56c3b3817](https://github.com/ChefKissInc/NootedRed/assets/49105934/2b1bc824-c47d-4e0e-97da-45db1cc3a25c)
![Screenshot_2024-04-01-18-10-30-84_99c04817c0de5652397fc8b56c3b3817](https://github.com/ChefKissInc/NootedRed/assets/49105934/9d9c508a-4f2e-4a4d-985f-9a77a505363f)
[opencore.zip](https://github.com/ChefKissInc/NootedRed/files/14822587/opencore.zip)
Thank you for your reply. I'll give it a try! Thank you!!

**Comment by VisualEhrmanntraut** [comment]
The OpenCore log is only OpenCore's logs. This is not of use to me.

**Comment by yuanxun9** [comment]
> The OpenCore log is only OpenCore's logs. This is not of use to me.

Hello, after unchecking the graphics card driver and entering the system, the wallpaper was changed to PNG format, but the fault still persists! Selected a few days of log files, please take a look at those that are useful! Thank you again, thank you for your hard work!
[Uploading 归档.zip…]()

**Comment by VisualEhrmanntraut** [comment]
You clicked comment before the file got a chance to upload.

**Comment by VisualEhrmanntraut** [comment]
Actually, are you using a DEBUG or RELEASE build?

**Comment by yuanxun9** [comment]
> 实际上，您使用的是DEBUG还是RELEASE构建？

Hello, it's RELEASE! Under NVRAM, 7C436110-AB2A-4BBBB-A880-FE41995C9F82 has changed several parameters - wegnoegpu keepsyms=1- vi2c force pooling debug=0x100 alcid=21- no_compat_check, disabled FeatureUnlock. kext and SMCRadeonGPU. kext are now functioning properly!

**Comment by VisualEhrmanntraut** [comment]
Okay, this is definitely not an issue with NootedRed; closing.
