### ISSUE TITLE
Graphics AMD radeon graphic 680m

### ISSUE THREAD

**Issue by vishu002** [ChefKissInc/NootedRed#246]
### macOS Version

Sonoma

### What is your CPU's model?

AMD RYZEN 6800hs

### Please describe the behaviour in detail.

when i insert Nred kexts file then after restart it can show amd radeon graphic 14mb, idk why showing low megabyte of iGPU , how to fix this problem ?

### What should've happened instead?

-

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

-

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [ ] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [ ] The bug only happens with NootedRed enabled.
- [ ] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
This is an RDNA iGPU, it is not supported yet. See #92

**Comment by vishu002** [comment]
how to solve this problem any idea?

**Comment by VisualEhrmanntraut** [comment]
Sir, there's no solution, it's plain not supported; you have to wait a while.

**Comment by vishu002** [comment]
OK sir ,i know sir this is more complicate to fix this problem ; can you pls tell me how much time to fixed this problem?
