### ISSUE TITLE
Rembrandt Support

### ISSUE THREAD

**Issue by vodangtue** [ChefKissInc/NootedRed#254]
### macOS Version

None

### What is your CPU's model?

AMD Ryzen 5 7535HS with Radeon Graphics

### Please describe the feature in detail.

I want NootedRed to be able to work with Rembrandt APU. Thanks!!

### What alternatives have you tried, if any?

I have tried NootedRed but I have read requirements again then I know it not supported :).

**Comment by VisualEhrmanntraut** [comment]
Duplicate of #92

**Comment by ExtremeXT** [comment]
@github-actions[bot] iMac1,1 2011 model bomb moment
