### ISSUE TITLE
Crashes on sonoma 14.4.1

### ISSUE THREAD

**Issue by mohddaniyaalsaifi** [ChefKissInc/NootedRed#257]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 5 3500u

### Please describe the behaviour in detail.

So after sucessful installation i logged in, everything seemed to be fine untill i opened the control centre, Mac os crashed 

### What should've happened instead?

It shouldn't have crashed and work like normal

**Comment by VisualEhrmanntraut** [comment]
Timed out waiting for response.
