### ISSUE TITLE
Menubar graphical glitch

### ISSUE THREAD

**Issue by Svetrikk** [ChefKissInc/NootedRed#258]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 5 4500U

### Please describe the behaviour in detail.

Sometimes the menubar gets colored. It usually happens when I open an app or something. The background of a button in a menubar gets only colored but disappears once I click on the button. The whole bar gets colored sometimes but also disappears when I open something in the menubar (eg. control center). Also this wasn't happening on Ventura but is on Sonoma.

![Untitled](https://github.com/ChefKissInc/NootedRed/assets/64600026/949dee0e-1d51-449f-9974-bb9c46bae0a9)

### What should've happened instead?

The menubar should be transparent

**Comment by TahsinFaiyaz30** [comment]
This happens because of insufficient VRAM. increase your VRAM to at least 2GB

**Comment by VisualEhrmanntraut** [comment]
Timed out waiting for response.
