### ISSUE TITLE
NootedRed Causes Hack to Panic on Startup

### ISSUE THREAD

**Issue by myusernameisvista** [ChefKissInc/NootedRed#259]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 5 4600H

### Please describe the behaviour in detail.

**Sonoma 14.4.1**

As I startup the hack, it loads fine until about 1/4 of the way then it restarts. It will do this every time unless nootedRed is disabled.

### What should've happened instead?

It should start up smoothly with no absolute conflict with Sonoma.

**Comment by VisualEhrmanntraut** [comment]
Timed out waiting for response.
