### ISSUE TITLE
Some display connections are not working after the colour banding fix

### ISSUE THREAD

**Issue by darthsian** [ChefKissInc/NootedRed#260]
### macOS Version

Ventura

### What is your CPU's model?

AMD Ryzen 7 5700U

### Please describe the behaviour in detail.

With the last commit (da6376b), the monitor connected via HDMI is not working. DisplayPort works fine.

### What should've happened instead?

The monitor via HDMI should work.

**Comment by darthsian** [comment]
The last commit where HDMI works without problems is 0c15616.

**Comment by VisualEhrmanntraut** [comment]
```sh
sudo rm /var/db/.com.apple.iokit.graphics
```
see if the issue persists, if yes, provide an AGDCDiagnose log using 
```sh
sudo /System/Library/Extensions/AppleGraphicsControl.kext/Contents/MacOS/AGDCDiagnose
```
and send it over here

**Comment by VisualEhrmanntraut** [comment]
AGDP printed no frame buffers which means it does not like your configuration, switch to a different SMBIOS

**Comment by darthsian** [comment]
I use iMac20,1 on all AMD Mini PCs and there has been no problem so far. Why has it worked without problems until now?

**Comment by VisualEhrmanntraut** [comment]
The getVendorInfo patch was broken until now, making AGDC think this is a dedicated GPU.

**Comment by darthsian** [comment]
Does it help if I send you the AGDCDiagnose log with commit 0c15616 where it still works?

**Comment by darthsian** [comment]
> The getVendorInfo patch was broken until now, making AGDC think this is a dedicated GPU.

Hmm, so what SMBIOS should we be using now if not iMac20,1? The iMacPro1,1 only has only dedicated GPU...

**Comment by VisualEhrmanntraut** [comment]
Try `MacBookPro16,3`.

**Comment by darthsian** [comment]
> Try `MacBookPro16,3`.

So, it doesn't strike me as a good idea to use a SMBIOS of laptop for a desktop.

**Comment by VisualEhrmanntraut** [comment]
mini PCs don't really strike me as AIOs either :^)

**Comment by techmare** [comment]
bruh ur mini pc literally have a laptop cpu 💀💀

**Comment by techmare** [comment]
literally a laptop motherboard  shrunken in size

**Comment by darthsian** [comment]
> Try `MacBookPro16,3`.

Ok, so on the `MacBookPro16,3` HDMI also unfortunately does not work :-/

**Comment by VisualEhrmanntraut** [comment]
That's weird.

**Comment by darthsian** [comment]
Isn't this a similar problem to the Intel Hackintosh where you have to use agdpmod=pikera boot argument with newer GPUs, otherwise the computer boots to a black screen?

**Comment by darthsian** [comment]
> this patch is already in place, along with another for making AGDP continue if there's only one FB

Look like we need some new agdpmod patch...

**Comment by SalmonPete** [comment]
I'm experiencing the same issue over HDMI on my 4700G Desktop, 14.4.1, iMac20,2, commit 2cf2ad6.

**Comment by VisualEhrmanntraut** [comment]
I have removed the patch at fault. Sorry for the inconvenience, I hate AGDP.

**Comment by SalmonPete** [comment]
Commit [e450df1] is still not detecting HDMI. [0c15616] is working great.

**Comment by VisualEhrmanntraut** [comment]
what

**Comment by VisualEhrmanntraut** [comment]
I reverted the problematic commit, and will reintroduce the fix properly once I fully understand what I'm supposed to do

**Comment by darthsian** [comment]
With the latest version I have the same problem again - HDMI does not work.

**Comment by VisualEhrmanntraut** [comment]
There have been no code changes for 2 months. That's impossible.

**Comment by darthsian** [comment]
So I reverted back to the last version again and now it works. I tried it several times before and it didn't work. I don't understand. Sorry for the false alarm.
