### ISSUE TITLE
Cannot play video which is downloaded in Sequoia

### ISSUE THREAD

**Issue by Kfkcome** [ChefKissInc/NootedRed#282]
### macOS Version

Sonoma

### What is your CPU's model?

AMD R7-4800H

### Please describe the behaviour in detail.

Cannot play video which is downloaded.The video stuck all the time like a pause, but the play button has been pressed.I have already disable the hardware acceleration.

![QQ_1721383433389](https://github.com/user-attachments/assets/1d166d08-1ea7-48a7-9982-60cc8cac4809)
(IINA video player)

### What should've happened instead?

I used many video player but all of them are in the same. When I used Sonoma , it was fine . It can play the video which is downloaded soomthly.

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

If it is needed, I can upload.

**Comment by VisualEhrmanntraut** [comment]
AppleALC broken in Sequoia = no sound = video playback fails

**Comment by Kfkcome** [comment]
> AppleALC broken in Sequoia = no sound = video playback fails

Yeah, it is true that appleAlC broken in my laptop . You are right , When I use the bluetooth earphone , it works fine.Thanks bro.
