### ISSUE TITLE
rDNA 2 Laptop

### ISSUE THREAD

**Issue by iltechalexone** [ChefKissInc/NootedRed#285]
### macOS Version

None

### What is your CPU's model?

AMD Ryzen 7 6800h

### Please describe the feature in detail.

Hello, when will be available SUPPORT for rDNA 2 Laptops? I have a Ryzen 7 6800h, with a 680m rembrandt...

PLEASE ADD THIS :)

### What alternatives have you tried, if any?

.

**Comment by MiranSS02** [comment]
is working on the 680M project abandoned now?

**Comment by VisualEhrmanntraut** [comment]
Hi. It’s not abandoned, just lower priority. I am the developer of all these kexts, I can’t magically just get stuff working. Just wait.

**Comment by MiranSS02** [comment]
Sorry to bother you, i was just curios since it's a great IGPU with that performance. hope we see it soon.
Thanks for your efforts.

**Comment by VisualEhrmanntraut** [comment]
You're welcome.
