### ISSUE TITLE
Ryzeb 5 7540U Support?

### ISSUE THREAD

**Issue by taqieallah** [ChefKissInc/NootedRed#287]
### macOS Version

None

### What is your CPU's model?

Ryzeb 5 7540U

### Please describe the feature in detail.

does nootedred support AMD Radeon™ 740M? im buying a new laptop but i want to check if its working,

### What alternatives have you tried, if any?

nope

**Comment by hg13bs** [comment]
not supported

**Comment by L123er** [comment]
Wait, they are also very hard.

**Comment by VisualEhrmanntraut** [comment]
Duplicate of #92
