### ISSUE TITLE
Is it possiable to support Zen 5 & RDNA 3.5?

### ISSUE THREAD

**Issue by muhammadbahaa2001** [ChefKissInc/NootedRed#305]
### macOS Version

Sequoia

### What is your CPU's model?

Ryzen AI 9 HX 370

### Please describe the feature in detail.

Is it possiable to support Ryzen AI 9 HX 370 and Radeon 890M iGPU?
I'm not rushing, I'm not asking you about ETA, or rushing you, I just wanted to know if that possable or not.

### What alternatives have you tried, if any?

No

**Comment by alvindimas05** [comment]
Probably not, at least not very soon. Check #92.
