### ISSUE TITLE
Very slow boot times

### ISSUE THREAD

**Issue by DeadBread99** [ChefKissInc/NootedRed#306]
### macOS Version

Sequoia

### What is your CPU's model?

AMD Ryzen 9 5900HX

### Please describe the behaviour in detail.

When i activate the NootedRed Kext my boot times get really long to like 5-10minutes and normally its jus about 1 minute this also didnt happen on ventura just after i updated to sequoia

### What should've happened instead?

It should boot just as fast as without the kext

**Comment by VisualEhrmanntraut** [comment]
@DeadBread99 Use the release build, not the debug one.

**Comment by DeadBread99** [comment]
I already do, also tried different versions but nothing changes

**Comment by VisualEhrmanntraut** [comment]
I don't know what to do in order to debug this

**Comment by VisualEhrmanntraut** [comment]
Maybe try `-NRedDebug` and see if there's anything going on while it's stuck

**Comment by VisualEhrmanntraut** [comment]
Timed out waiting for response.
