### ISSUE TITLE
Hardware Acceleration and Freezes

### ISSUE THREAD

**Issue by ual1n** [ChefKissInc/NootedRed#311]
### macOS Version

Sonoma 14.7

### What is your CPU's model?

Ryzen 5 4600G - Vega 7 (iGPU)

### Please describe the behaviour in detail.

System applications are working properly and this Kext has helped me a lot, however, external applications that require hardware acceleration are literally freezing or bugging, as is the case with Brave, so I decided to send this report.

Other applications such as Notion, Discord and Telegram, freeze, but load normally after a while.

![Screenshot 2024-10-15 at 09 01 02](https://github.com/user-attachments/assets/932470ae-144b-4d21-aa1f-c37ae11ffca2)

### What should've happened instead?

The apps should open normally, but after clicking, the window is shown, but the system freezes (except for the mouse pointer). As mentioned before, some apps freeze and then start working again, and others, like Brave, bug, change color and the entire interface is broken.

**Comment by hg13bs** [comment]
@ual1n issue is known, see #158 and for now patch the app(s) using AMDHelper, also use Safari for browser
