### ISSUE TITLE
freeze when wanted to change profile picture

### ISSUE THREAD

**Issue by moishiteru** [ChefKissInc/NootedRed#313]
### macOS Version

Sequoia

### What is your CPU's model?

Ryzen 5 3500u

### Please describe the behaviour in detail.

when i want to change anything on system preferences especially avatar for the profile then notebook freeze and i must force to shutdown 

### What should've happened instead?

the notebook freeze completely

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

[DiagnosticReports.zip](https://github.com/user-attachments/files/17440216/DiagnosticReports.zip)

**Comment by VisualEhrmanntraut** [comment]
duplicate of #235
