### ISSUE TITLE
After the update on November 8, 2024, the model of the graphic adapter is incorrectly detected ( Ryzen 5 4600H)

### ISSUE THREAD

**Issue by PhilVlady** [ChefKissInc/NootedRed#324]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 4600H

### Please describe the behaviour in detail.

After the update on November 8, 2024, the model of the graphic adapter is incorrectly detected ( Ryzen 5 4600H).
It is now determined not as Vega 6, but as AMD Radeon RX.

![Screenshot at Nov 09 00-02-05](https://github.com/user-attachments/assets/2a135b35-1caa-4643-bd25-bead683e763b)
![Screenshot at Nov 09 00-02-38](https://github.com/user-attachments/assets/252b78d9-b267-4382-8801-42e576b30e9c)

### What should've happened instead?

Should be defined as Vega.

**Comment by VisualEhrmanntraut** [comment]
Not a bug; these models are extracted directly from the Windows driver. Complain to AMD.

**Comment by PhilVlady** [comment]
But until today's update there was no display "Radeon RX".
This is a screenshot from a few hours ago.
![Screenshot at Nov 08 22-38-52](https://github.com/user-attachments/assets/32d47acd-f159-4648-ab13-af6399aab864)

**Comment by VisualEhrmanntraut** [comment]
Radeon RX is correct. I just made it consistent, after I updated the models.
<img width="1624" alt="image" src="https://github.com/user-attachments/assets/6f8ed25a-1fcc-4a97-8f91-a2a0a687cb22">

**Comment by PhilVlady** [comment]
Do I need to change some values ​​to get the correct look or just leave it as is? Thanks!

**Comment by VisualEhrmanntraut** [comment]
"AMD Radeon RX Graphics" just means there is no specific branding name for your card. No additional configuration is required.

**Comment by PhilVlady** [comment]
Thank you!
