### ISSUE TITLE
The "Chess" application does not start.

### ISSUE THREAD

**Issue by PhilVlady** [ChefKissInc/NootedRed#325]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 5 4600H

### Please describe the behaviour in detail.

The "Chess" application does not start. An error window immediately pops up. Although acceleration is enabled and works, as far as I can see.
![Screenshot at Nov 09 00-02-38](https://github.com/user-attachments/assets/2a028299-f868-4d88-91e6-8469e8f9cfe9)

### What should've happened instead?

Srart the "Chess" application.

**Comment by VisualEhrmanntraut** [comment]
Please stop making unnecessary bug reports. As stated in the website, you need to increase your VRAM size to 1GB or more.

**Comment by PhilVlady** [comment]
The processor has 512 MB of video memory allocated at the physical level. This value cannot be increased. I understand you. Thank you!

**Comment by VisualEhrmanntraut** [comment]
If you haven't tried Smokeless UMAF, you can try increasing the size using that. If it doesn't work, then you're out of luck for now, unless I find a way to let macOS dynamically allocate the memory.

**Comment by PhilVlady** [comment]
Ooooh!!! You are a great Guru! I didn't know about the "Smokeless UMAF" program! Now everything is great! I didn't expect such fast and qualified help! My gratitude! 
![photo_2024-11-09_01-37-06](https://github.com/user-attachments/assets/0291f624-ac87-4f82-94ab-bc7e0bc26f7c)
![photo_2024-11-09_01-36-59](https://github.com/user-attachments/assets/f3b362b7-f34f-46ca-badb-12acb004b7c8)

**Comment by VisualEhrmanntraut** [comment]
@PhilVlady You’re welcome, feel free to join the Telegram linked in our website or create a new post in the discussions tab for further questions regarding NootedRed.
