### ISSUE TITLE
Drops frames severely.

### ISSUE THREAD

**Issue by lwh110221** [ChefKissInc/NootedRed#326]
### macOS Version

Sequoia

### What is your CPU's model?

AMD R7-5800H

### Please describe the feature in detail.

When you open the desktop scheduler, if there are several windows on the desktop and then open the startup desk to turn the page, it drops frames severely.

### What alternatives have you tried, if any?

none

**Comment by VisualEhrmanntraut** [comment]
https://chefkissinc.github.io/applehax/nootedred/#prerequisites
