### ISSUE TITLE
Screen Mirroring Resulted in a Black External Screen

### ISSUE THREAD

**Issue by EraserCN** [ChefKissInc/NootedRed#334]
### macOS Version

All supported macOS versions

### What is the precise OS version on which the bug is occurring?

12-15.0

### What is your CPU's model?

AMD Risen 3500U

### Describe the unexpected behaviour in detail.

I tried to use my TV as an external display using screen mirroring to Apple TV. However, the external display went black even though macOS told me that it had successfully connected to the Apple TV and vice versa. 

Please note that video AirPlay does work fine on the same device. My WiFi Card is AX200, and Screen Mirroring worked fine on my desktop RX6800XT Hackintosh with the same wifi card model.

### What should've happened instead?

The TV screen should display as an external display.

### Attach any logs related to this issue. For example .gpuRestart, .panic, etc files.

There's neither .gpuRestart nor .panic file, macOS though everything worked fine.

### Issue Submission Terms

- [x] You have made sure that there are no other reports about this bug.
- [x] You do not use configurator software (e.g. OpenCore Auxiliary Tools, OpenCore Configurator).
- [x] You have made your own EFI according to the ChefKiss Hackintosh Guide.
- [x] You are not using any software that may conflict, including, but not limited to, OpenCore Legacy Patcher, BFixup, WhateverGreen.
- [x] You acknowledge that violation of these terms may result in your issue being closed or your user being blocked from the organisation.

**Comment by VisualEhrmanntraut** [comment]
#28
