### ISSUE TITLE
Android emulators on QEMU won't start

### ISSUE THREAD

**Issue by elfametesar** [ChefKissInc/NootedRed#339]
### macOS Version

macOS Sequoia

### What is the precise OS version on which the bug is occurring?

15.0 24A335

### What is your CPU's model?

Ryzen 7 5800H

### Describe the unexpected behaviour in detail.

I am currently working with Flutter on Visual Studio, and wanted to run an Android emulator from Android Studio, however it seems to crash complaining about not finding an accelarator. I am not sure if it's a normal behavior given the current state of the NootedRed development, so decided to ask. iOS emulators on XCode seems to work fine, not that they are the same obviously.

### What should've happened instead?

The emulator should have launched

### Attach any logs related to this issue. For example .gpuRestart, .panic, etc files.

Starting device daemon...
[ERR] The Android emulator exited with code -9 after startup
[ERR] Android emulator stderr:
[ERR] initialize: Supports id properties, got a vulkan device UUID
[ERR] objc[10861]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb459c0598) and /Users/elfa/Library/Android/sdk/emulator/lib64/gles_angle/libGLESv2.dylib (0x309f44748). One of the two will be used. Which one is undefined.
[ERR] HVF error: HV_ERROR
[ERR] qemu-system-x86_64: failed to initialize HVF: Invalid argument
[ERR] Failed to open the hax module
[ERR] No accelerator found.
[ERR] qemu-system-x86_64: failed to initialize HAX: Operation not supported by device
[ERR] Address these issues and try again.

### Issue Submission Terms

- [x] You have made sure that there are no other reports about this bug.
- [x] You do not use configurator software (e.g. OpenCore Auxiliary Tools, OpenCore Configurator).
- [x] You have made your own EFI according to the ChefKiss Hackintosh Guide.
- [x] You are not using any software that may conflict, including, but not limited to, OpenCore Legacy Patcher, BFixup, WhateverGreen.
- [x] You acknowledge that violation of these terms may result in your issue being closed or your user being blocked from the organisation.

**Comment by VisualEhrmanntraut** [comment]
“HVF” -> Hypervisor.framework, aka: AppleHV, which only supports Intel CPUs.
