### ISSUE TITLE
Updating to last version results in a bootable hackintosh with disabled hardware acceleration

### ISSUE THREAD

**Issue by Mirarchi** [ChefKissInc/NootedRed#341]
### macOS Version

macOS Sonoma

### What is the precise OS version on which the bug is occurring?

14.1.2

### What is your CPU's model?

Ryzen 7 4800H

### Describe the unexpected behaviour in detail.

Updating to the latest nightly results in a booting hackintosh but with the hardware acceleration disabled. My kext backup (dated July 2024) works correctly. Should I do update something else? (maybe lilu or the Sonoma version itself?)

### What should've happened instead?

The update process should result in a bootable hackintosh with accelerated graphics.

### Issue Submission Terms

- [x] You have made sure that there are no other reports about this bug.
- [x] You do not use configurator software (e.g. OpenCore Auxiliary Tools, OpenCore Configurator).
- [x] You have made your own EFI according to the ChefKiss Hackintosh Guide.
- [x] You are not using any software that may conflict, including, but not limited to, OpenCore Legacy Patcher, BFixup, WhateverGreen.
- [x] You acknowledge that violation of these terms may result in your issue being closed or your user being blocked from the organisation.

**Comment by VisualEhrmanntraut** [comment]
Update. All. Your. Kexts. (In particular, Lilu in this case)
